language: node_js
os:
    - linux
    - windows
    - osx
node_js:
    - "stable"
    - "6"
    - "5"
sudo: false
before_script:
  - npm install -g codecov gulp istanbul
script:
    - gulp lint
    - gulp test
    - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
    - codecov
env:
    - NODE_ENV=ci LOGGER_FILE_PATH=./info.test.ci.log
cache:
  directories:
    - node_modules
after_success:
  - bash <(curl -s https://codecov.io/bash)