language: node_js
os:
    - linux
    - windows
    - osx
node_js:
    - "stable"
    - "6"
    - "5"
sudo: false
before_script:
  - npm install -g gulp
script:
    - gulp lint
    - gulp test
env:
    - NODE_ENV=ci
    - LOGGER_FILE_PATH=./logs/info.test.log
after_success:
  - bash <(curl -s https://codecov.io/bash)